./compiler < tests/rules.board
./compiler < tests/greaterthantest.board
./compiler < tests/rule.board
./compiler < tests/dsa.board
./compiler < tests/elseiftest.board
./compiler < tests/ifelsetest.board
./compiler < tests/piecetest.board
./compiler < tests/playertest.board
./compiler < tests/binop.board
./compiler < tests/ruleCheck.board
./compiler < tests/helloworld.board
./compiler < tests/BigTest.board
./compiler < tests/wrongtypecast.board
